export const ROOM_SESSION_EXCEPTION_CODES = {
  ROOM_SESSION_NOT_FOUND: 'ROOM_SESSION-0001',
  ROOM_ALREADY_IN_USE: 'ROOM_SESSION-0002',
  ROOM_SESSION_ALREADY_ENDED: 'ROOM_SESSION-0003',
  INVALID_ROOM_SESSION_STATUS: 'ROOM_SESSION-0004',
} as const;

type RoomSessionExceptionCode = (typeof ROOM_SESSION_EXCEPTION_CODES)[keyof typeof ROOM_SESSION_EXCEPTION_CODES];

export const ROOM_SESSION_EXCEPTION_MESSAGES: Record<RoomSessionExceptionCode, string> = {
  [ROOM_SESSION_EXCEPTION_CODES.ROOM_SESSION_NOT_FOUND]: '세션을 찾을 수 없습니다',
  [ROOM_SESSION_EXCEPTION_CODES.ROOM_ALREADY_IN_USE]: '해당 방은 이미 사용중입니다',
  [ROOM_SESSION_EXCEPTION_CODES.ROOM_SESSION_ALREADY_ENDED]: '세션이 이미 종료되었습니다',
  [ROOM_SESSION_EXCEPTION_CODES.INVALID_ROOM_SESSION_STATUS]: '유효하지 않은 세션 상태입니다',
};
