export const STORE_ROOM_EXCEPTION_CODES = {
  STORE_ROOM_NOT_FOUND: 'STORE_ROOM-0001',
  STORE_ROOM_NUMBER_DUPLICATED: 'STORE_ROOM-0002',
} as const;

type StoreRoomExceptionCode = (typeof STORE_ROOM_EXCEPTION_CODES)[keyof typeof STORE_ROOM_EXCEPTION_CODES];

export const STORE_ROOM_EXCEPTION_MESSAGES: Record<StoreRoomExceptionCode, string> = {
  [STORE_ROOM_EXCEPTION_CODES.STORE_ROOM_NOT_FOUND]: '방을 찾을 수 없습니다',
  [STORE_ROOM_EXCEPTION_CODES.STORE_ROOM_NUMBER_DUPLICATED]: '이미 존재하는 방 번호입니다',
};
