export const STORE_TIME_PLAN_EXCEPTION_CODES = {
  STORE_TIME_PLAN_NOT_FOUND: 'STORE_TIME_PLAN-0001',
  STORE_TIME_PLAN_NAME_DUPLICATED: 'STORE_TIME_PLAN-0002',
} as const;

type StoreTimePlanExceptionCode =
  (typeof STORE_TIME_PLAN_EXCEPTION_CODES)[keyof typeof STORE_TIME_PLAN_EXCEPTION_CODES];

export const STORE_TIME_PLAN_EXCEPTION_MESSAGES: Record<StoreTimePlanExceptionCode, string> = {
  [STORE_TIME_PLAN_EXCEPTION_CODES.STORE_TIME_PLAN_NOT_FOUND]: '요금제를 찾을 수 없습니다',
  [STORE_TIME_PLAN_EXCEPTION_CODES.STORE_TIME_PLAN_NAME_DUPLICATED]: '이미 존재하는 요금제 이름입니다',
};
