export const STORE_FOOD_CATEGORY_EXCEPTION_CODES = {
  STORE_FOOD_CATEGORY_NOT_FOUND: 'STORE_FOOD_CATEGORY-0001',
  STORE_FOOD_CATEGORY_NAME_DUPLICATED: 'STORE_FOOD_CATEGORY-0002',
} as const;

type StoreFoodCategoryExceptionCode =
  (typeof STORE_FOOD_CATEGORY_EXCEPTION_CODES)[keyof typeof STORE_FOOD_CATEGORY_EXCEPTION_CODES];

export const STORE_FOOD_CATEGORY_EXCEPTION_MESSAGES: Record<StoreFoodCategoryExceptionCode, string> = {
  [STORE_FOOD_CATEGORY_EXCEPTION_CODES.STORE_FOOD_CATEGORY_NOT_FOUND]: '카테고리를 찾을 수 없습니다',
  [STORE_FOOD_CATEGORY_EXCEPTION_CODES.STORE_FOOD_CATEGORY_NAME_DUPLICATED]: '이미 존재하는 카테고리 이름입니다',
};
